import type { Metadata } from "next";
import { JetBrains_Mono, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-JetBrains-Mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MERN Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-theme="system"
      className={cn("h-full", "antialiased", jetBrainsMono.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
        {children}
        <Toaster position="top-right"></Toaster>
        </ThemeProvider>
      </body> 
    </html>
  );
}