// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { url } from "node:inspector";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Corrected the property name and environment variable syntax
    // Added a fallback value for DATABASE_URL to handle undefined cases
    url: process.env.DATABASE_URL || "fallback_database_url",
  },
});
